<?php
class jPressZoneCacheService{

    public static function get_list_cache_config( $offset = 0, $limit = NULL )
    {
        global $wpdb, $jpress_zone_cache;
        $sql = "SELECT SQL_CALC_FOUND_ROWS * FROM ". $jpress_zone_cache->table_cache_config . " WHERE 1=1 " ;
        $sql .=  " ORDER BY id ASC " ;

        if(!is_null($limit)){
            $sql .= " LIMIT " . $offset . ", " . $limit ;
        }
        $results = array();
        $results["data"] = $wpdb->get_results($sql);
        $sql = "SELECT FOUND_ROWS() as nbrTotal;";
        $results["total"] = $wpdb->get_var($sql);

        return  $results;
    }

    function get_list_caches($offset = 0, $limit = NULL)
    {
        global $wpdb, $jpress_zone_cache;
        $sql = "SELECT SQL_CALC_FOUND_ROWS * FROM ".$jpress_zone_cache->table_caches . " WHERE 1=1 " ;
        $sql .=  " ORDER BY id ASC " ;

        if(!is_null($limit) && $limit>0){
            $sql .= " LIMIT " . $offset . ", " . $limit ;
        }
        $results = array();
        $results["data"] = $wpdb->get_results($sql);
        $sql = "SELECT FOUND_ROWS() as nbrTotal;";
        $results["total"] = $wpdb->get_var($sql);

        return  $results;
    }

    public static function set_cache_config($name, $role, $langue, $zone_file )
    {
        global $wpdb, $jpress_zone_cache;
        $wpdb->insert($jpress_zone_cache->table_cache_config, array(
            'name' => sanitize_title($name),
            'role' => $role,
            'langue' => $langue,
            'zone_file' => $zone_file
        ));
    }

    public static function delete_cache_config($ids)
    {
        global $wpdb, $jpress_zone_cache;
        $ids = implode(',',$ids);
        $sql = "DELETE FROM {$jpress_zone_cache->table_cache_config} WHERE id IN(" . $ids .")";
        $wpdb->query($sql);
    }

    public static function delete_caches($ids)
    {
        global $wpdb, $jpress_zone_cache;
        $ids = implode(',',$ids);
        $sql = "DELETE FROM {$jpress_zone_cache->table_caches} WHERE id IN(" . $ids .")";
        $wpdb->query($sql);
    }

    public static function get_cache_by( $field, $id )
    {
        global $wpdb, $jpress_zone_cache;
        $sql = "SELECT * FROM {$jpress_zone_cache->table_cache_config} WHERE {$field} = '" . $id . "'";
        return $wpdb->get_row($sql);
    }


    public static function generate_caches($ids)
    {
        global $wpdb, $jpress_zone_cache;
        $ids = implode(',',$ids);
        $sql = "SELECT * FROM {$jpress_zone_cache->table_cache_config} WHERE id IN(" . $ids .")";
        $results = $wpdb->get_results($sql);
        foreach ($results as $result) {
            self::generate_cache($result);
        }
    }

    public static function generate_cache($cache){
        $dirname = WP_PLUGIN_DIR . '/jpress-zone-cache/zone_file/';

        //langue wpml case
        /*if ($cache->langue == '1' && class_exists('SitePress')){
            global $sitepress, $jzc_lang,  $wp_query;
            $langues = $sitepress->get_active_languages();
            foreach ( $langues as $lang) {
                ob_start();
                include ($dirname . $cache->zone_file );
                $output = ob_get_contents();
                ob_end_clean();
                //jzc_save_caches($output);

            }
        }*/
    }

    public static function save_caches($html, $cache_id, $role = NULL, $langue = NULL){
        global $wpdb, $jpress_zone_cache;
        $postvar = array(
            'cache_id' => $cache_id,
            'html' => '<!--ZONE CACHE BEGIN-->' . $html . '<!--ZONE CACHE END :  generated by jPress-Zone-Cache on ' . date('Y-m-d H:i:s') . '-->'
        );
        if(!is_null($role)){
            $postvar['role'] = $role;
        }
        if(!is_null($langue)){
            $postvar['langue'] = $langue;
        }
        $wpdb->insert($jpress_zone_cache->table_caches, $postvar);
    }

    public static function get_cache( $cache_slug, $role = NULL, $lang = NULL ){
        global $wpdb, $jpress_zone_cache;
        $sql = "SELECT tc.html FROM {$jpress_zone_cache->table_caches} AS tc
    		INNER JOIN 	{$jpress_zone_cache->table_cache_config} AS tcc ON tc.cache_id =  tcc.id
		    WHERE tcc.name = '" . $cache_slug ."' ";
        if($role)
            $sql .= " AND tc.role = '" . $role . "' " ;
        if($lang)
            $sql .= " AND tc.langue = '" . $lang . "' " ;
        $sql .=  " LIMIT 1" ;

        return $wpdb->get_var($sql);
    }

    public static function purge_cache($slug, $lang = NULL, $role=NULL )
    {
        global $wpdb, $jpress_zone_cache;
        $cache = jPressZoneCacheService::get_cache_by('name',$slug);

        $sql = "DELETE FROM {$jpress_zone_cache->table_caches} WHERE cache_id = " . $cache->id ;
        if ( !is_null($lang) ){
            $sql.= " AND langue ='" . $lang."' ";
        }
        if ( !is_null($role) ){
            $sql.= " AND role ='" . $role."' ";
        }
        $wpdb->query($sql);
    }

}