advanced-custom-fields
wck-custom-fields-and-custom-post-types-creator
acf-repeater
acf-gallery
advanced-custom-fields-taxonomy-field-add-on
wysija-newsletters
newsletter-manager
acategory-dropdown-list
regenerate-thumbnails
reorder-post-within-categories
taxonomy-terms-order
global-posts-ordering
cpt-onomies
tinymce-templates
lh-user-taxonomies
wp-super-cache
wp-smushit
multisite-language-switcher
woocommerce
wp-e-commerce
